#Лабораторна робота №1
#Студента групи МІТ-31 (підгрупа 2)
#Маніла Дмитра Олексійовича

In [ ]:
#%pip install pandas
#%pip install numpy
#%pip install matplotlib
#%pip install seaborn

#Завдання
1.  NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Використати arange, random.
2.  Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...))
3.  Matplotlib (створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)
4.  Відповіді оформити .ipynb документом
5.  Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab1 де має бути .ipynb файл та необхідні файли з даними

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

1.NumPy

#Create

In [19]:
array1 = np.arange(0,20,3)
array2 = np.random.randint(20, size=(array1.size))
array1 = np.append(array1,33)
array2 = np.append(array2,15)
print("array1.add(33):", array1)
print("array2.add(15):", array2)


array1.add(33): [ 0  3  6  9 12 15 18 33]
array2.add(15): [17  0  7  4  1  1  6 15]


#Update


In [20]:
array1[2] = 22
array2[5] = 92
array1[0] = 15
array2[6] = 13
print("array1:", array1)
print("array2:", array2)


array1: [15  3 22  9 12 15 18 33]
array2: [17  0  7  4  1 92 13 15]


#Delete
@mandmit

In [21]:
array1 = np.delete(array1,np.random.randint(array1.size))
array2 = np.delete(array2,np.random.randint(array2.size))
print("array1:", array1)
print("array2:", array2)


array1: [15  3 22  9 12 15 33]
array2: [17  0  7  4  1 92 15]


#Scalar


In [22]:
array1 = np.multiply(array1,2)
array2 = np.power(array2,2)
print("array1*2:", array1)
print("array2**2:", array2)


array1*2: [30  6 44 18 24 30 66]
array2**2: [ 289    0   49   16    1 8464  225]


#Vector


In [23]:
array3 = np.add(array2,array1)
print("array3=array2+array1:", array3)
array3 = np.subtract(array3,array1)
print("array3-array1:", array3)
array2 = np.subtract(array2,array1)
print("array2-array1:", array2)
print("array1:", array1)


array3=array2+array1: [ 319    6   93   34   25 8494  291]
array3-array1: [ 289    0   49   16    1 8464  225]
array2-array1: [ 259   -6    5   -2  -23 8434  159]
array1: [30  6 44 18 24 30 66]


#Matrix


In [43]:
size = np.random.randint(10)
matrix = np.random.randint(30,size = (size,size))
print("Matrix: ", matrix, sep="\n")


Matrix: 
[[27 11  7 11]
 [24 20 17 27]
 [ 9 18  7 10]
 [21  2  4  9]]
Matrix1: 
[[27 11  7 11]
 [24 20 17 27]
 [ 9 18  7 10]
 [21  2  4  9]]


In [51]:
matrix = np.zeros((3,6))
print("Matrix: ", matrix, sep="\n")
matrix = np.ones((3,6))
print("Matrix: ", matrix, sep="\n")

Matrix: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Matrix: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [53]:
matrix = np.random.randint(30,size = (size,size))
matrix1 = np.random.randint(30,size = (size,size))
print("Matrix: ", matrix, sep="\n")
print("Matrix1: ", matrix1, sep="\n")
print("Matrix-Matrix1: ", matrix-matrix1, sep="\n")
print("Matrix+Matrix1: ", matrix+matrix1, sep="\n")
print("Matrix*Matrix1: ", matrix*matrix1, sep="\n")
print("Matrix/Matrix1: ", matrix/matrix1, sep="\n")

Matrix: 
[[26 11 13 29]
 [ 4 14 24 10]
 [27 18 24 23]
 [ 5 13  6 26]]
Matrix1: 
[[12  2  6 15]
 [13 11 17 16]
 [14 27  6 17]
 [ 5 13 19 15]]
Matrix-Matrix1: 
[[ 14   9   7  14]
 [ -9   3   7  -6]
 [ 13  -9  18   6]
 [  0   0 -13  11]]
Matrix+Matrix1: 
[[38 13 19 44]
 [17 25 41 26]
 [41 45 30 40]
 [10 26 25 41]]
Matrix*Matrix1: 
[[312  22  78 435]
 [ 52 154 408 160]
 [378 486 144 391]
 [ 25 169 114 390]]
Matrix/Matrix1: 
[[2.16666667 5.5        2.16666667 1.93333333]
 [0.30769231 1.27272727 1.41176471 0.625     ]
 [1.92857143 0.66666667 4.         1.35294118]
 [1.         1.         0.31578947 1.73333333]]


2.Pandas

In [27]:
customers = pd.read_csv("FyntraCustomerData.csv")
customers.head()

Email  \
0      mstephenson@fernandez.com   
1              hduke@hotmail.com   
2               pallen@yahoo.com   
3        riverarebecca@gmail.com   
4  mstephens@davidson-herman.com   

                                             Address            Avatar  \
0     835 Frank Tunnel\r\nWrightmouth, MI 82180-9605            Violet   
1   4547 Archer Common\r\nDiazchester, CA 06566-8576         DarkGreen   
2  24645 Valerie Unions Suite 582\r\nCobbborough,...            Bisque   
3  1414 David Throughway\r\nPort Jason, OH 22070-...       SaddleBrown   
4  14023 Rodriguez Passage\r\nPort Jacobville, PR...  MediumAquaMarine   

   Avg_Session_Length  Time_on_App  Time_on_Website  Length_of_Membership  \
0           34.497268    12.655651        39.577668              4.082621   
1           31.926272    11.109461        37.268959              2.664034   
2           33.000915    11.330278        37.110597              4.104543   
3           34.305557    13.717514        36.721283              3.120179   
4           33.330673    12.795189        37.536653              4.446308   

   Yearly_Amount_Spent  
0           587.951054  
1           392.204933  
2           487.547505  
3           581.852344  
4           599.406092

In [28]:
customers.describe()

Avg_Session_Length  Time_on_App  Time_on_Website  Length_of_Membership  \
count          500.000000   500.000000       500.000000            500.000000   
mean            33.053194    12.052488        37.060445              3.533462   
std              0.992563     0.994216         1.010489              0.999278   
min             29.532429     8.508152        33.913847              0.269901   
25%             32.341822    11.388153        36.349257              2.930450   
50%             33.082008    11.983231        37.069367              3.533975   
75%             33.711985    12.753850        37.716432              4.126502   
max             36.139662    15.126994        40.005182              6.922689   

       Yearly_Amount_Spent  
count           500.000000  
mean            499.314038  
std              79.314782  
min             256.670582  
25%             445.038277  
50%             498.887875  
75%             549.313828  
max             765.518462

In [29]:
customers.iloc()
customers.loc()