#Лабораторна робота №1
#Студента групи МІТ-31 (підгрупа 2)
#Маніла Дмитра Олексійовича

In [ ]:
#%pip install pandas
#%pip install numpy
#%pip install matplotlib
#%pip install seaborn

#Завдання
1.  NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Використати arange, random.
2.  Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...))
3.  Matplotlib (створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)
4.  Відповіді оформити .ipynb документом
5.  Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab1 де має бути .ipynb файл та необхідні файли з даними

In [2]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
#%matplotlib inline
#customers = pd.read_csv("FyntraCustomerData.csv")

1.NumPy

In [40]:
array1 = np.arange(0,20,3)
array2 = np.random.randint(20, size=(array1.size))
print("array1:", array1)
print("array2:", array2)
#CRUD
array1[2] = 22
array1 = np.append(array1,33)
array2 = np.append(array2,15)
print("array1:", array1)
print("array2:", array2)
array1 = np.delete(array1,np.random.randint(array1.size))
array2 = np.delete(array2,np.random.randint(array2.size))
print("array1:", array1)
print("array2:", array2)
#Scalar
array1 = np.multiply(array1,2)
array2 = np.power(array2,2)
print("array1:", array1)
print("array2:", array2)
#Vector
array3 = np.add(array2,array1)
array3 = np.subtract(array3,array1)
array2 = np.subtract(array2,array1)
print("array1:", array1)
print("array2:", array2)
print("array3:", array3)
#Matrix
matrix = np.random.randint(30,size = (4,3))
print("Matrix: ", matrix, sep="\n")


array1: [ 0  3  6  9 12 15 18]
array2: [ 5 10 17  8 16 12  1]
array1: [ 0  3 22  9 12 15 18 33]
array2: [ 5 10 17  8 16 12  1 15]
array1: [ 3 22  9 12 15 18 33]
array2: [ 5 10 17 16 12  1 15]
array1: [ 6 44 18 24 30 36 66]
array2: [ 25 100 289 256 144   1 225]
array1: [ 6 44 18 24 30 36 66]
array2: [ 19  56 271 232 114 -35 159]
array3: [ 25 100 289 256 144   1 225]
Matrix: 
[[24  9  4]
 [ 9 16 24]
 [24 22 13]
 [ 8 18  6]]
